services:
  postgres:
    image: postgis/postgis:17-3.4-alpine
    container_name: postgres-db-redpostmen
    restart: unless-stopped
    environment:
      POSTGRES_USER: redpostmen
      POSTGRES_PASSWORD: redpostmen
      POSTGRES_DB: redpostmen_pg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql

volumes:
  pgdata:
